version: '3.8'

services:
  web:
    build: ./web
    container_name: wordpress
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html:cached
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_URL: http://localhost:8000
      WORDPRESS_TITLE: ''
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: password
      WORDPRESS_ADMIN_EMAIL:
    depends_on:
      - db
    networks:
      - cms-network

  db:
    build: ./db
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db/storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - cms-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8001:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - db
    networks:
      - cms-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token <YOUR_CLOUDFLARE_TUNNEL_TOKEN>
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge
