version: '3.3'

services:
  web:
    build: ./web
    volumes:
      - ./wordpress:/var/www/html:cached
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_URL: http://localhost:8000
      WORDPRESS_TITLE: ''
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: password
      WORDPRESS_ADMIN_EMAIL:
    networks:
      - acc_network

  db:
    build: ./db
    volumes:
      - ./db/storage:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - acc_network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - acc_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiY2I0OGM1NGI4OTVhMjlmNDc3YjdmNzc5YTQ5Y2FiMGYiLCJ0IjoiNDUwZTdjNTItNjU4Ny00Nzc0LWIzYmMtMTkzYmNjNTZkYzBkIiwicyI6IlpXUmlNMkV5TmpVdE1UTTBZaTAwWW1NMUxX>
    networks:
      - acc_network

networks:
  acc_network:
    driver: bridge
